import { User, Post, DashboardStats, Activity, ServiceCategory } from '@/types';

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: '1',
    name: 'María González',
    email: 'maria@example.com',
    phone: '+34 600 123 456',
    avatar: '/avatars/maria.jpg',
    isProvider: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Carlos Rodríguez',
    email: 'carlos@example.com',
    phone: '+34 600 789 012',
    avatar: '/avatars/carlos.jpg',
    isProvider: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
];

// Dummy Posts
export const dummyPosts: Post[] = [
  {
    id: '1',
    title: 'Alquiler de Bicicletas de Montaña en Sierra Nevada',
    description: 'Disfruta de las mejores rutas de montaña con nuestras bicicletas profesionales. Incluye casco, herramientas y mapa de rutas.',
    category: 'Bicycle Rental',
    price: 25,
    currency: 'ARS',
    location: 'Sierra Nevada, Granada',
    images: ['/images/bike1.jpg', '/images/bike2.jpg'],
    isActive: true,
    userId: '1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    bikeType: 'Mountain',
    duration: 'Day',
    includes: ['Casco', 'Herramientas', 'Mapa de rutas', 'Seguro'],
    requirements: ['Documento de identidad', 'Depósito de $50'],
  },
  {
    id: '2',
    title: 'Alquiler de Coche Familiar en Barcelona',
    description: 'Coche espacioso y confortable para toda la familia. Perfecto para explorar Barcelona y sus alrededores.',
    category: 'Car Rental',
    price: 45,
    currency: 'ARS',
    location: 'Barcelona, Cataluña',
    images: ['/images/car1.jpg', '/images/car2.jpg'],
    isActive: true,
    userId: '2',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
    carType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 7,
    includes: ['Seguro completo', 'GPS', 'Silla de bebé'],
    requirements: ['Carnet de conducir', 'Tarjeta de crédito', 'Edad mínima 25 años'],
  },
  {
    id: '3',
    title: 'Excursión a la Alhambra de Granada',
    description: 'Visita guiada completa a la Alhambra con guía oficial. Incluye entrada, transporte y tiempo libre.',
    category: 'Excursions',
    price: 65,
    currency: 'ARS',
    location: 'Granada, Andalucía',
    images: ['/images/alhambra1.jpg', '/images/alhambra2.jpg'],
    isActive: true,
    userId: '1',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    duration: '4 horas',
    groupSize: 15,
    includes: ['Entrada a la Alhambra', 'Guía oficial', 'Transporte', 'Agua'],
    itinerary: ['Recogida en hotel', 'Visita a los Palacios Nazaríes', 'Jardines del Generalife', 'Tiempo libre'],
    requirements: ['Reserva anticipada', 'Documento de identidad'],
  },
  {
    id: '4',
    title: 'Experiencia de Flamenco en Sevilla',
    description: 'Vive la auténtica experiencia flamenca en el corazón de Sevilla. Espectáculo íntimo con artistas locales.',
    category: 'Experiences',
    price: 35,
    currency: 'ARS',
    location: 'Sevilla, Andalucía',
    images: ['/images/flamenco1.jpg', '/images/flamenco2.jpg'],
    isActive: true,
    userId: '2',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
    duration: '2 horas',
    groupSize: 20,
    includes: ['Espectáculo flamenco', 'Bebida', 'Tapas', 'Fotos'],
    activities: ['Espectáculo de baile', 'Música en vivo', 'Degustación de tapas'],
    requirements: ['Reserva con 24h de antelación'],
  },
  {
    id: '5',
    title: 'Hotel Boutique en el Centro de Madrid',
    description: 'Hotel de 4 estrellas en el corazón de Madrid. Habitaciones elegantes con todas las comodidades.',
    category: 'Hotel Stay',
    price: 120,
    currency: 'ARS',
    location: 'Madrid, Comunidad de Madrid',
    images: ['/images/hotel1.jpg', '/images/hotel2.jpg'],
    isActive: true,
    userId: '1',
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
    roomType: 'Double',
    amenities: ['WiFi gratuito', 'Desayuno incluido', 'Gimnasio', 'Spa'],
    checkIn: '15:00',
    checkOut: '11:00',
    policies: ['Cancelación gratuita hasta 24h antes', 'No fumadores'],
  },
  {
    id: '6',
    title: 'Casa Rural en los Picos de Europa',
    description: 'Hermosa casa rural con vistas espectaculares a los Picos de Europa. Perfecta para desconectar.',
    category: 'Vacation Home Rental',
    price: 150,
    currency: 'ARS',
    location: 'Picos de Europa, Asturias',
    images: ['/images/casa1.jpg', '/images/casa2.jpg'],
    isActive: true,
    userId: '2',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
    propertyType: 'House',
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ['Chimenea', 'Cocina completa', 'Terraza', 'Parking'],
    checkIn: '16:00',
    checkOut: '10:00',
    policies: ['Estancia mínima 2 noches', 'Mascotas permitidas'],
  },
  {
    id: '7',
    title: 'Camping Glamping en la Costa Brava',
    description: 'Experiencia de camping de lujo con tiendas equipadas y todas las comodidades de un hotel.',
    category: 'Camping Stay',
    price: 80,
    currency: 'ARS',
    location: 'Costa Brava, Girona',
    images: ['/images/camping1.jpg', '/images/camping2.jpg'],
    isActive: true,
    userId: '1',
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
    siteType: 'Glamping',
    maxGuests: 4,
    amenities: ['Cama doble', 'Electricidad', 'Baño privado', 'Restaurante'],
    checkIn: '14:00',
    checkOut: '11:00',
    policies: ['Reserva anticipada recomendada', 'Mascotas no permitidas'],
  },
];

// Dummy Dashboard Stats
export const dummyDashboardStats: DashboardStats = {
  totalPosts: 7,
  activePosts: 6,
  totalViews: 1247,
  totalBookings: 23,
  monthlyRevenue: 2840,
  recentActivity: [
    {
      id: '1',
      type: 'post_created',
      message: 'Nuevo post creado: "Camping Glamping en la Costa Brava"',
      timestamp: new Date('2024-02-20T10:30:00'),
      postId: '7',
    },
    {
      id: '2',
      type: 'booking_received',
      message: 'Nueva reserva recibida para "Alquiler de Bicicletas de Montaña"',
      timestamp: new Date('2024-02-19T15:45:00'),
      postId: '1',
    },
    {
      id: '3',
      type: 'view_increased',
      message: 'Aumento significativo de vistas en "Excursión a la Alhambra"',
      timestamp: new Date('2024-02-18T09:15:00'),
      postId: '3',
    },
    {
      id: '4',
      type: 'post_updated',
      message: 'Post actualizado: "Hotel Boutique en el Centro de Madrid"',
      timestamp: new Date('2024-02-17T14:20:00'),
      postId: '5',
    },
  ],
};

// Service Categories
export const serviceCategories: ServiceCategory[] = [
  // Alojamiento
  'Hotel',
  'Casa',
  'Departamento',
  'Cabaña',
  'Camping',
  'Domo',
  // Alquiler de vehículos
  'Alquiler de autos',
  'Alquiler de bicicletas',
  'Alquiler de kayaks',
  // Otros servicios - Clases e instructorados
  'Clases de Esquí',
  'Clases de snowboard',
  'Clases de surf',
  'Clases de wingfoil',
  'Clases de wing surf',
  // Otros servicios - Alquileres
  'Alquiler equipo de esquí',
  'Alquiler equipo de snowboard',
  'Alquiler ropa de nieve',
  'Alquiler equipo de surf',
  'Alquiler equipo de wingfoil',
  'Alquiler equipo de wing surf',
  'Alquiler de carpa',
  'Alquiler de sombrilla',
  'Alquiler',
  // Otros servicios - Excursiones
  'Excursiones lacustres',
  'Excursiones terrestres',
  'Experiencias 4x4',
  'Cabalgatas',
  'Excursiones aéreas',
  // Otros servicios - Fotografía
  'Vuelo de drone',
  'Fotografía',
];

// Main category to subcategory mapping
export const mainCategoryMapping = {
  'alojamiento': [
    'Hotel',
    'Casa',
    'Departamento',
    'Cabaña',
    'Camping',
    'Domo',
  ],
  'alquiler-vehiculos': [
    'Alquiler de autos',
    'Alquiler de bicicletas',
    'Alquiler de kayaks',
  ],
  'otros-servicios': [
    'Clases de Esquí',
    'Clases de snowboard',
    'Clases de surf',
    'Clases de wingfoil',
    'Clases de wing surf',
    'Alquiler equipo de esquí',
    'Alquiler equipo de snowboard',
    'Alquiler ropa de nieve',
    'Alquiler equipo de surf',
    'Alquiler equipo de wingfoil',
    'Alquiler equipo de wing surf',
    'Alquiler de carpa',
    'Alquiler de sombrilla',
    'Alquiler',
    'Excursiones lacustres',
    'Excursiones terrestres',
    'Experiencias 4x4',
    'Cabalgatas',
    'Excursiones aéreas',
    'Vuelo de drone',
    'Fotografía',
  ],
};

// Otros Servicios grouped structure for optgroups
export const otrosServiciosGroups = {
  'Clases e instructorados': [
    'Clases de Esquí',
    'Clases de snowboard',
    'Clases de surf',
    'Clases de wingfoil',
    'Clases de wing surf',
  ],
  'Alquileres': [
    'Alquiler equipo de esquí',
    'Alquiler equipo de snowboard',
    'Alquiler ropa de nieve',
    'Alquiler equipo de surf',
    'Alquiler equipo de wingfoil',
    'Alquiler equipo de wing surf',
    'Alquiler de carpa',
    'Alquiler de sombrilla',
    'Alquiler',
  ],
  'Excursiones': [
    'Excursiones lacustres',
    'Excursiones terrestres',
    'Experiencias 4x4',
    'Cabalgatas',
    'Excursiones aéreas',
  ],
  'Fotografía': [
    'Vuelo de drone',
    'Fotografía',
  ],
};

// Category-specific field configurations
export const categoryFields = {
  // Alojamiento
  'Hotel': {
    roomType: ['Individual', 'Doble', 'Suite', 'Familiar'],
    stars: ['3 estrellas', '4 estrellas', '5 estrellas'],
  },
  'Casa': {
    maxPeople: 'Cantidad máxima de personas',
  },
  'Departamento': {
    maxPeople: 'Cantidad máxima de personas',
  },
  'Cabaña': {
    maxPeople: 'Cantidad máxima de personas',
  },
  'Camping': {
    siteType: ['Tienda', 'Caravana', 'Cabaña', 'Glamping'],
    maxPeople: 'Cantidad máxima de personas',
  },
  'Domo': {
    domeType: ['Domo geodésico', 'Domo transparente', 'Domo rústico'],
    maxPeople: 'Cantidad máxima de personas',
  },
  
  // Alquiler de vehículos
  'Alquiler de autos': {
    carType: ['Económico', 'Compacto', 'SUV', 'Lujo', 'Furgoneta'],
    transmission: ['Manual', 'Automático'],
    fuelType: ['Gasolina', 'Diésel', 'Eléctrico', 'Híbrido'],
    seats: ['2 plazas', '4 plazas', '5 plazas', '7+ plazas'],
    // New vehicle-specific fields
    maxPeople: 'Cantidad de personas',
    pickupTime: 'Horario de retiro',
    returnTime: 'Horario de devolución',
    // Checkbox options
    deliveryPoints: 'Entrega en puntos a convenir',
    childSeat: 'Silla para niños',
    snowChains: 'Cadenas para nieve',
    countryPermission: 'Permiso para salir del país',
    spareWheel: 'Rueda de auxilio',
    gnc: 'GNC',
  },
  'Alquiler de bicicletas': {
    bikeType: ['Montaña', 'Carretera', 'Ciudad', 'Eléctrica'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Casco', 'Herramientas', 'Mapa', 'Seguro', 'Candado'],
    // New vehicle-specific fields
    maxPeople: 'Cantidad de personas',
    pickupTime: 'Horario de retiro',
    returnTime: 'Horario de devolución',
    // Checkbox options
    deliveryPoints: 'Entrega en puntos a convenir',
    helmet: 'Casco',
    vest: 'Chaleco',
    extraHours: 'Horas extras',
  },
  'Alquiler de kayaks': {
    kayakType: ['Individual', 'Doble', 'Inflable', 'Rígido'],
    duration: ['Hora', 'Medio día', 'Día completo'],
    includes: ['Chaleco salvavidas', 'Remo', 'Instrucciones', 'Seguro'],
    // New vehicle-specific fields
    maxPeople: 'Cantidad de personas',
    pickupTime: 'Horario de retiro',
    returnTime: 'Horario de devolución',
    // Checkbox options
    deliveryPoints: 'Entrega en puntos a convenir',
    lifeJacket: 'Poncho salvavidas',
    paddles: 'Remos y salvaremos',
  },
  
  // Otros servicios
  'Clases de Esquí': {
    servicio: ['Clases de Esquí'],
    level: ['Principiante', 'Intermedio', 'Avanzado', 'Experto'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    includes: ['Instructor certificado', 'Equipo básico', 'Seguro', 'Transporte'],
  },
  'Clases de snowboard': {
    servicio: ['Clases de snowboard'],
    level: ['Principiante', 'Intermedio', 'Avanzado', 'Experto'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    includes: ['Instructor certificado', 'Equipo básico', 'Seguro', 'Transporte'],
  },
  'Clases de surf': {
    servicio: ['Clases de surf'],
    level: ['Principiante', 'Intermedio', 'Avanzado', 'Experto'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    includes: ['Instructor certificado', 'Equipo básico', 'Seguro', 'Transporte'],
  },
  'Clases de wingfoil': {
    servicio: ['Clases de wingfoil'],
    level: ['Principiante', 'Intermedio', 'Avanzado', 'Experto'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    includes: ['Instructor certificado', 'Equipo básico', 'Seguro', 'Transporte'],
  },
  'Clases de wing surf': {
    servicio: ['Clases de wing surf'],
    level: ['Principiante', 'Intermedio', 'Avanzado', 'Experto'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    includes: ['Instructor certificado', 'Equipo básico', 'Seguro', 'Transporte'],
  },
  'Alquiler equipo de esquí': {
    servicio: ['Alquiler equipo de esquí'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Equipo completo', 'Mantenimiento', 'Seguro'],
  },
  'Alquiler equipo de snowboard': {
    servicio: ['Alquiler equipo de snowboard'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Equipo completo', 'Mantenimiento', 'Seguro'],
  },
  'Alquiler ropa de nieve': {
    servicio: ['Alquiler ropa de nieve'],
    duration: ['Día', 'Semana'],
    includes: ['Ropa completa', 'Accesorios', 'Limpieza'],
  },
  'Alquiler equipo de surf': {
    servicio: ['Alquiler equipo de surf'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Tabla', 'Neopreno', 'Seguro'],
  },
  'Alquiler equipo de wingfoil': {
    servicio: ['Alquiler equipo de wingfoil'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Equipo completo', 'Instrucciones', 'Seguro'],
  },
  'Alquiler equipo de wing surf': {
    servicio: ['Alquiler equipo de wing surf'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Equipo completo', 'Instrucciones', 'Seguro'],
  },
  'Alquiler de carpa': {
    servicio: ['Alquiler de carpa'],
    duration: ['Día', 'Semana'],
    includes: ['Carpa', 'Accesorios', 'Instrucciones'],
  },
  'Alquiler de sombrilla': {
    servicio: ['Alquiler de sombrilla'],
    duration: ['Día', 'Semana'],
    includes: ['Sombrilla', 'Base', 'Instalación'],
  },
  'Alquiler': {
    servicio: ['Alquiler'],
    duration: ['Hora', 'Día', 'Semana'],
    includes: ['Equipo', 'Mantenimiento', 'Seguro'],
  },
  'Excursiones lacustres': {
    servicio: ['Excursiones lacustres'],
    duration: ['Medio día', 'Día completo'],
    groupSize: ['Individual', 'Grupo pequeño (2-6)', 'Grupo mediano (7-15)', 'Grupo grande (16+)'],
    includes: ['Guía', 'Equipo', 'Seguro', 'Transporte'],
  },
  'Excursiones terrestres': {
    servicio: ['Excursiones terrestres'],
    duration: ['Medio día', 'Día completo'],
    groupSize: ['Individual', 'Grupo pequeño (2-6)', 'Grupo mediano (7-15)', 'Grupo grande (16+)'],
    includes: ['Guía', 'Equipo', 'Seguro', 'Transporte'],
  },
  'Experiencias 4x4': {
    servicio: ['Experiencias 4x4'],
    duration: ['Medio día', 'Día completo'],
    groupSize: ['Individual', 'Grupo pequeño (2-6)', 'Grupo mediano (7-15)', 'Grupo grande (16+)'],
    includes: ['Vehículo 4x4', 'Conductor', 'Seguro', 'Combustible'],
  },
  'Cabalgatas': {
    servicio: ['Cabalgatas'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    level: ['Principiante', 'Intermedio', 'Avanzado'],
    includes: ['Guía', 'Casco', 'Seguro', 'Instrucciones'],
  },
  'Excursiones aéreas': {
    servicio: ['Excursiones aéreas'],
    duration: ['Medio día', 'Día completo'],
    groupSize: ['Individual', 'Grupo pequeño (2-6)', 'Grupo mediano (7-15)', 'Grupo grande (16+)'],
    includes: ['Vuelo', 'Piloto', 'Seguro', 'Equipo'],
  },
  'Vuelo de drone': {
    servicio: ['Vuelo de drone'],
    duration: ['1 hora', '2 horas', 'Medio día'],
    includes: ['Drone', 'Piloto certificado', 'Edición de video', 'Fotos'],
  },
  'Fotografía': {
    servicio: ['Fotografía'],
    duration: ['1 hora', '2 horas', 'Medio día', 'Día completo'],
    includes: ['Fotógrafo profesional', 'Edición', 'Entrega digital', 'Fotos impresas'],
  },
};

// Category-specific amenities/features
export const categoryAmenities = {
  // Alojamiento categories
  'Hotel': [
    'Aire acondicionado',
    'Calefacción',
    'Estacionamiento privado',
    'Parrilla',
    'Petfriendly',
    'Apto discapacidad',
    'WiFi',
    'Cámaras de vigilancia',
    'Ropa de cama',
    'Toallas',
    'Servicio de limpieza',
  ],
  'Casa': [
    'Aire acondicionado',
    'Calefacción',
    'Estacionamiento privado',
    'Parrilla',
    'Petfriendly',
    'Apto discapacidad',
    'WiFi',
    'Cámaras de vigilancia',
    'Ropa de cama',
    'Toallas',
    'Servicio de limpieza',
  ],
  'Departamento': [
    'Aire acondicionado',
    'Calefacción',
    'Estacionamiento privado',
    'Parrilla',
    'Petfriendly',
    'Apto discapacidad',
    'WiFi',
    'Cámaras de vigilancia',
    'Ropa de cama',
    'Toallas',
    'Servicio de limpieza',
  ],
  'Cabaña': [
    'Aire acondicionado',
    'Calefacción',
    'Estacionamiento privado',
    'Parrilla',
    'Petfriendly',
    'Apto discapacidad',
    'WiFi',
    'Cámaras de vigilancia',
    'Ropa de cama',
    'Toallas',
    'Servicio de limpieza',
  ],
  'Camping': [
    'Aire acondicionado',
    'Calefacción',
    'Estacionamiento privado',
    'Parrilla',
    'Petfriendly',
    'Apto discapacidad',
    'WiFi',
    'Cámaras de vigilancia',
    'Ropa de cama',
    'Toallas',
    'Servicio de limpieza',
  ],
  'Domo': [
    'Aire acondicionado',
    'Calefacción',
    'Estacionamiento privado',
    'Parrilla',
    'Petfriendly',
    'Apto discapacidad',
    'WiFi',
    'Cámaras de vigilancia',
    'Ropa de cama',
    'Toallas',
    'Servicio de limpieza',
  ],
  
  // Alquiler de vehículos
  'Alquiler de autos': [
    'Entrega en puntos a convenir',
    'Silla para niños',
    'Cadenas para nieve',
    'Permiso para salir del país',
    'Rueda de auxilio',
    'GNC',
  ],
  'Alquiler de bicicletas': [
    'Entrega en puntos a convenir',
    'Casco',
    'Chaleco',
    'Horas extras',
  ],
  'Alquiler de kayaks': [
    'Entrega en puntos a convenir',
    'Poncho salvavidas',
    'Remos y salvaremos',
  ],
  
  // Otros servicios
  'Clases de Esquí': [
    'Clase individual',
    'Clase a grupo cerrado',
    'Clase grupal abierta al público',
    'Clase por hora',
    'Clase por packs de tiempo definido',
    'No incluye pase al centro de esquí',
    'No incluye equipos ni ropa',
  ],
  'Clases de snowboard': [
    'Clase individual',
    'Clase a grupo cerrado',
    'Clase grupal abierta al público',
    'Clase por hora',
    'Clase por packs de tiempo definido',
    'No incluye pase al centro de esquí',
    'No incluye equipos ni ropa',
  ],
  'Clases de surf': [
    'Clase individual',
    'Clase a grupo cerrado',
    'Clase grupal abierta al público',
    'Clase por hora',
    'Clase por packs de tiempo definido',
    'No incluye equipos ni ropa',
  ],
  'Clases de wingfoil': [
    'Clase individual',
    'Clase a grupo cerrado',
    'Clase grupal abierta al público',
    'Clase por hora',
    'Clase por packs de tiempo definido',
    'No incluye equipos ni ropa',
  ],
  'Clases de wing surf': [
    'Clase individual',
    'Clase a grupo cerrado',
    'Clase grupal abierta al público',
    'Clase por hora',
    'Clase por packs de tiempo definido',
    'No incluye equipos ni ropa',
  ],
  'Alquiler equipo de esquí': [
    'Entrega en puntos a convenir',
    'Mantenimiento incluido',
    'Seguro incluido',
    'Equipo de última generación',
  ],
  'Alquiler equipo de snowboard': [
    'Entrega en puntos a convenir',
    'Mantenimiento incluido',
    'Seguro incluido',
    'Equipo de última generación',
  ],
  'Alquiler ropa de nieve': [
    'Entrega en puntos a convenir',
    'Limpieza incluida',
    'Accesorios incluidos',
    'Ropa de alta calidad',
  ],
  'Alquiler equipo de surf': [
    'Entrega en puntos a convenir',
    'Tabla de calidad',
    'Neopreno incluido',
    'Seguro incluido',
  ],
  'Alquiler equipo de wingfoil': [
    'Entrega en puntos a convenir',
    'Equipo completo',
    'Instrucciones básicas',
    'Seguro incluido',
  ],
  'Alquiler equipo de wing surf': [
    'Entrega en puntos a convenir',
    'Equipo completo',
    'Instrucciones básicas',
    'Seguro incluido',
  ],
  'Alquiler de carpa': [
    'Entrega en puntos a convenir',
    'Accesorios incluidos',
    'Instrucciones de montaje',
    'Carpa de calidad',
  ],
  'Alquiler de sombrilla': [
    'Entrega en puntos a convenir',
    'Base incluida',
    'Instalación incluida',
    'Sombrilla de calidad',
  ],
  'Alquiler': [
    'Entrega en puntos a convenir',
    'Mantenimiento incluido',
    'Seguro incluido',
    'Equipo de calidad',
  ],
  'Excursiones lacustres': [
    'Guía certificado',
    'Equipo incluido',
    'Seguro incluido',
    'Transporte incluido',
  ],
  'Excursiones terrestres': [
    'Guía certificado',
    'Equipo incluido',
    'Seguro incluido',
    'Transporte incluido',
  ],
  'Experiencias 4x4': [
    'Conductor experimentado',
    'Vehículo en perfecto estado',
    'Seguro incluido',
    'Combustible incluido',
  ],
  'Cabalgatas': [
    'Guía certificado',
    'Casco incluido',
    'Seguro incluido',
    'Instrucciones básicas',
  ],
  'Excursiones aéreas': [
    'Piloto certificado',
    'Equipo de seguridad',
    'Seguro incluido',
    'Vuelo panorámico',
  ],
  'Vuelo de drone': [
    'Piloto certificado',
    'Edición de video',
    'Fotos de alta calidad',
    'Entrega rápida',
  ],
  'Fotografía': [
    'Fotógrafo profesional',
    'Edición incluida',
    'Entrega digital',
    'Fotos impresas opcionales',
  ],
};

// Facturación options for all categories
export const facturacionOptions = [
  'Emite factura C',
  'Emite factura A',
  'No emite factura',
]; 